extends "res://tests/run_tests.gd"
## Reutiliza os contratos existentes, sem duplicar a implementação dos testes.
func _correr_tudo() -> void:
	LojaCatalogo.gratis = false
	print("COMBATE TESTE teste_combat_lab")
	await teste_combat_lab()
	print("COMBATE TESTE teste_combat_lab_combos")
	await teste_combat_lab_combos()
	print("COMBATE TESTE teste_combat_lab_pd_real")
	await teste_combat_lab_pd_real()
	print("COMBATE TESTE teste_combat_lab_pd_contrato")
	await teste_combat_lab_pd_contrato()
	print("COMBATE TESTE teste_contrato_dano_producao")
	await teste_contrato_dano_producao()
	print("COMBATE TESTE teste_core_combate_producao")
	await teste_core_combate_producao()
	print("COMBATE TESTE teste_enemy_contract_legado_inerte")
	await teste_enemy_contract_legado_inerte()
	print("COMBATE TESTE teste_enemy_contract_hurtbox")
	await teste_enemy_contract_hurtbox()
	print("COMBATE TESTE teste_enemy_contract_guarda_opt_in")
	await teste_enemy_contract_guarda_opt_in()
	print("COMBATE TESTE teste_goblin_piloto_estrutura")
	await teste_goblin_piloto_estrutura()
	print("COMBATE TESTE teste_goblin_piloto_isolamento")
	await teste_goblin_piloto_isolamento()
	print("COMBATE TESTE teste_goblin_piloto_comportamento")
	await teste_goblin_piloto_comportamento()
	print("COMBATE TESTE teste_goblin_piloto_ttk")
	await teste_goblin_piloto_ttk()
	print("COMBATE TESTE teste_golem_piloto_estrutura")
	await teste_golem_piloto_estrutura()
	print("COMBATE TESTE teste_golem_piloto_comportamento")
	await teste_golem_piloto_comportamento()
	print("COMBATE TESTE teste_golem_piloto_ttk")
	await teste_golem_piloto_ttk()
	print("COMBATE TESTE teste_energy_instrumentation")
	await teste_energy_instrumentation()
	print("COMBATE TESTE teste_combat_lab_clamp")
	await teste_combat_lab_clamp()
	print("COMBATE TESTE teste_combat_lab_antispam")
	await teste_combat_lab_antispam()
	print("COMBATE TESTE teste_combat_lab_balanco")
	await teste_combat_lab_balanco()
	for f in _falhas:
		printerr("FALHOU: ", f)
	print("COMBATE REGRESSAO: 20 testes, %d falhas" % _falhas.size())
	get_tree().quit(1 if not _falhas.is_empty() else 0)
